### ISSUE TITLE
modifying las files to remove useless alignments

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#176]
Jason:  what do you think of this idea?  (Having a program that would remove useless alignments from the las files).  Would then make the las files much smaller (around 1/30 the size, by my experiments).  So LAsort/merge/LA4Falcon would run MUCH faster, we'd use less disk space...

Reducing -M is not working so well for me.  Reduce it too much, and daligner crashes with:
Warning: Block size too big, index occupies more than 1/4 of desired memory allocation

And if you reduce it just a little, it will make the files smaller, but it will eliminate useful alignments also.

What was the other daligner parameter I should experiment with?

**Comment by pb-jchin** [comment]
if you reduce -M, you will need to reduce the block size in some cases.  Reducing useless alignments is a good idea. The question is to predice what are useless well.

**Comment by dgordon562** [comment]
Thanks!  How do I reduce the block size?

**Comment by pb-jchin** [comment]
check the opiton for DBsplit

**Comment by dgordon562** [comment]
Is that what you did to get such little .las files?  What did you reduce it to?

**Comment by pb-jchin** [comment]
I use more strigent alignment parameters (-k -h -w opiton for daligner) to reduct false hit rate and keep the las files small. In the mean time, I am doing experiment on LA4Falcon.c to reduce alignment caused by repeats. It will help to solve the consensus I/O issue.  Also, it some filtering logic is working well, we can put them into daligner's `fliter.c` to reduce the file size from the beginning too.

**Comment by dgordon562** [comment]
Thanks!

What -k -h and -w parameters do you use for human/primate?
