### ISSUE TITLE
Reduce and improve logging

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/FALCON#194]

**Comment by dgordon562** [comment]
Yes, please.  I suggest that stdout/stderr should not have 10 lines of output every second.  If there is great support for being able to tell that Falcon is still running, then just print a "." (with no carriage return) every 20 seconds or so.  So it would just have:

......

Otherwise stdout and stderr should report when a new job is submitted.  That is useful information but with the current stdout/stderr, you can't see that because there is so much scrolling by.

Best wishes,
David

**Comment by pb-cdunn** [comment]
Try `0.4.1`.
