### ISSUE TITLE
Falcon error: pypeflow.controller.TaskFailureError: 'Counted 1 failures.'

### ISSUE THREAD

**Issue by ishengtsai** [PacificBiosciences/FALCON#202]
Hi,

Since installation we've successfully run a few bacterial assemblies with good results. We are now attempting to run an 180Mb assembly using ~70X Pacbio data. But running a few times we've always encountered "Falcon error: pypeflow.controller.TaskFailureError: 'Counted 1 failures.'". We've run the job under local and looking at the log of the particular job we still didn't really understand. Please see the screenshot below and help is appreciated. 

![image](https://cloud.githubusercontent.com/assets/5182142/10036049/ebe610b0-61d3-11e5-83c6-03b8432a43f4.png)

Best,
Jason

**Comment by pb-jchin** [comment]
it is not easy to see what is going. What could happned is thery might be a fail block daligner jobs. Do you think if you can find the related log for the related job inside the `sge_log` directory?

**Comment by ishengtsai** [comment]
The sge_log directory is empty as the job is run =local. Is there any other location that I can look for?

Best,
Jason

**Comment by pb-jchin** [comment]
I would suggest to take a look at all *.las inside all job_* directory to see if some of them are unusually small.

**Comment by ishengtsai** [comment]
Found it! There are quite a few which exited prematurely. Please see below.

![image](https://cloud.githubusercontent.com/assets/5182142/10041301/e950e216-6215-11e5-95b0-bde378bc6b31.png)

**Comment by pb-jchin** [comment]
You can use "-M" parameter for daligner to control the memory usage. You might have too many jobs running at the same time exhausting the memory.  Also, you should control the number of jobs that can be run concurrently.

**Comment by afinit** [comment]
I ran into the same issue with the 'local' mode. I've figured out my memory issues and I've since been able to dial in the CPU usage a little better, but when I ran falcon with the below config on a machine with 56 physical cores and 512GB of RAM, there was a CPU load of 200+. I'm not seeing where I'm telling it to use 4 cores per job.

Also, when I run falcon with 25 concurrent jobs, there is a CPU load of 85. So there is scaling based on this number.

```
  1 [General]
  2
  3 job_type = local
  4
  5 # list of files of the initial bas.h5 files
  6 input_fofn = input.fofn
  7
  8 input_type = raw
  9
 10 # The length cutoff used for seed reads used for initial mapping
 11 length_cutoff = 2000
 12
 13 # The length cutoff used for seed reads use for pre-assembly
 14 length_cutoff_pr = 2000
 15
 16 pa_concurrent_jobs = 56
 17 ovlp_concurrent_jobs = 56
 18
 19 # set -dal32 to have less jobs
 20 # min read length can be set with the -l option
 21 pa_HPCdaligner_option =  -v -dal8 -t16 -e.70 -l1000 -s1000
 22 ovlp_HPCdaligner_option = -v -dal8 -t32 -h60 -e.96 -l500 -s1000
 23
 24 # set -s400 to define block sizes of 400Mb for a smaller number of jobs because this will be running on a machine that can handle jobs that run for longer
 25 pa_DBsplit_option = -x500 -s40
 26 ovlp_DBsplit_option = -x500 -s40
 27
 28 falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 3 --local_match_count_threshold 2 --max_n_read 200 --n_core 6
 29
 30 overlap_filtering_setting = --max_diff 2000 --max_cov 2000 --min_cov 2 --bestn 10
 31
```

**Comment by pb-cdunn** [comment]
Currently, the number of threads in a local job is controlled by these:

* `pa_concurrent_jobs`
  * 1st daligner runs
* `cns_concurrent_jobs`
  * 1st consensus runs
* `ovlp_concurrent_jobs`
  * 2nd daligner runs and everything else

For 56 CPUs, you should start with14 for the 1st and 3rd, since daligner uses 4 threads by job. However, daligner is often i/o limited, so you might go higher, as you've seen.

You might improve overall performance by running in `/tmp`, to reduce i/o latency (or at least to kind to your network). This is possible even with job_type=local.

    use_tmpdir = true
