### ISSUE TITLE
Tool for  PacBio Data Denovo assembly of Diploid plant genome ( 500 mb size) having 52x coverage

### ISSUE THREAD

**Issue by sudhirjadhao** [PacificBiosciences/FALCON#203]
Hello Everyone
I have query regarding tool  for de novo assembly. I have plant genome data at 52X coverage. The genome size is around  500 mb 

I used HGAP (RS_HGAP_assembly2, RS_HGAP_assembly3 , RS_preassembly 2) tool through SMRT portal it giving me error of "ERROR! Reading fasta files greater than 4Gbytes is not supported" .

Then I used falcon it run successfully  but in assembly folder the all files are empty except preads.ovl, 2-asm-falcon/run_falcon_asm.sh.log 

Can anyone please suggest me tool for assembly for data having 58x coverage and predicted genome size is 500mb .

**Comment by pb-jchin** [comment]
why do you have single fasta files > 4Gb?

**Comment by sudhirjadhao** [comment]
I have 38 cell data. for assembly step I am giving all 38 cell data as input.

**Comment by pb-jchin** [comment]
The code is currenly designed to take non-concanted files as input. Do you hve the original *.subreads.fasta files? Or, you need to write some script to split the files.

**Comment by sudhirjadhao** [comment]
Thank you for your kind reply,
I have subreads.fasta file and also you can tell for which data I have to write code. I will do that just explain me what need to be done where I am going wrong

**Comment by sudhirjadhao** [comment]
Can I run HGAP   assembly  in breaks with 5 cells at a time. after completing assembly for 38 cells . can I merge these assembly. To get final assembly that I want

**Comment by pb-jchin** [comment]
@sudhirjadhao while it is possible to do incremental assembly, it is currently hard to have a simple implementation for any computation architecture. There is an experimental incremental assembly implemented in the code, but no one uses it at this moment. Due to the tricky implementation, it is not robust, so I don't recommend doing it for now. We can re-open this issue once we figure out a better way to implement this kind of feature.
