### ISSUE TITLE
Error trapping with pipes

### ISSUE THREAD

**Issue by flowers9** [PacificBiosciences/FALCON#220]
There's a slight error detection problem with the pread generating bash scripts.  In those, you pipe the output from LA4Falcon through fc_consensus.py.  Unfortunately, if LA4Falcon dies with an error, the script continues rather than hitting the trap, because error returns from pipelines are ignored unless it's from the last command in the pipeline.

The fix is a simple one - have fc_consensus.py start LA4Falcon as a subcommand, and then check the return code when it finishes.  If it's non-zero, then exit with a non-zero value, which the trap then catches.  This only requires a couple of modifications - consensus.py needs a new parameter (the command line to run to get input from), and run.py needs to generate the appropriate script to use it.

import subprocess
import shlex

...

    parser.add_argument('--input_command', help='command to generate input [none, stdin read]')

...

    if args.input_command == None:
        input = sys.stdin
    else:
        input_args = shlex.split(args.input_command)
        input_program = subprocess.Popen(input_args, bufsize=32768, stdout=subprocess.PIPE)
        input = input_program.stdout

...

    # if we ran the command, check its return value, and error on error
    if args.input_command != None:
        input_program.wait()
        if input_program.returncode != 0:
            exit(input_program.returncode)

and then pass "input" as a parameter to get_seq_data.

**Comment by pb-jchin** [comment]
I like it. I use the stdin initially because it helps to debug. I can generate a smale portion of the data in file to test `fc_consensus.py` easily. Of course, there are many way to import data for processing.  @pb-cdunn, what do you think about this? If we change to call `LA4falcon` internally, we also have to change other code too.  @flowers9, do you have a branch that I can do some quick test to check out the behavior?

**Comment by flowers9** [comment]
Sorry, but I'm not familiar with using github, I just pull down tar files and make changes locally.  My copy also has a number of other unrelated changes at this point - you might have trouble figuring out which were related to this issue if I did manage to upload my current code.

I do believe that the above covers most of the changes, though.  The change in run.py would be very minor - just move the LA4Falcon command from the beginning of the pipe to a command line option to fc_consensus.py.  LA4Falcon itself doesn't require any changes.

**Comment by pb-cdunn** [comment]
This refers to the code here:
* https://github.com/PacificBiosciences/FALCON/blob/master/src/py/run_support.py#L408

Yes, the pipe (`|`) is suppressing errors. I was about to change this too, since I am now looking into **fc_consensus**.

@flowers9, your suggestion is an attempt to avoid writing an intermediate file to disk, right? Yes, good goal, since this is a lot of data. But your solution could have a problem with buffer-size. That's a common pitfall with Python subprocess, which for me has been more trouble than it's worth.

In fact, since there is so much data, I'm not sure that Python is sufficient for fc_consensus. We might re-write, or switch to dazcon (pbdagcon) since it might be the runtime bottleneck.

Anyway, for this particular problem, the solution is simple:

    set -o pipefail

However, fc_consensus can continue to run. If there is much buffered data, that could be a problem. I've long wanted better error-detection in fc_consensus. Still, I *think* fc_consensus will fail pretty quickly. And the the rest of the workflow will end.

I can make that change quickly, but you might be better off testing that yourself first. You can modify a generated bash-file and run it.
