### ISSUE TITLE
daligner job names

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#247]
chris--you were right.  decimal is better than hex because it immediately tells you the total # of jobs and how many are remaining.  Just eliminate the leading 0's and the name will be short enough.  There is nothing wrong with a directory "job_1"  or a job name rj_1

**Comment by pb-cdunn** [comment]
Ok. But it's still sequential in hexadecimal now. You just have to convert hex to dec in your head. :smirk:

There is another benefit to hex: 2/3 as many digits.

You're really looking for likely uniqueness, and a way to achieve that would be to *reverse* the digits, so the least significant digit is first.

I'll further shorten that leading part of the job-name, but later. I plan to encode a checksum into the job-name so that we can satisfy another of your requirements: To "re-attach" to running qsub jobs when FALCON crashes and restarts. (We also plan to have much faster restarts soon.)

For now, maybe there is a better solution to this problem. You *can* see the full job name; use `qstat -r`.

**Comment by pb-jchin** [comment]
In general, I prefer to have left padded zero as that it is good to make some sorting easier for many cases. However, whether padding zeros on the left is good is really depending on case by case.
