### ISSUE TITLE
What do LAsort and LAmerge do?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#326]
Hi, Chris,

https://dazzlerblog.wordpress.com/ is not very clear, but I'm sure you know...

This is my guess:  LAsort sorts alignments by the (smaller?) index of the reads in raw_reads.db

LAmerge essentially concatenates the las files--it doesn't merge 2 alignments into one (???)

???

Thanks!
David

**Comment by pb-cdunn** [comment]
* **LAsort** sorts A-reads (where each alignment has A and B) by begin index (and secondarily by end index, I think).
* **LAmerge** just merges files, but it's really a merge-sort. No, alignments are not altered.

Fundamentally, daligner is really very simple. I like that Gene has separate components because that makes everything both easy to understand and easy to map to hardware. The .las files are just 'alignments', referring back into the DB. Each alignment is calculated and stored only at intervals -- called trace-points -- which keeps disk-space low while still allowing full alignment calculations to be done in very quickly in practice.

**Comment by dgordon562** [comment]
What is an "A-read"?

So if I understand correctly, if you have reads A, B, C, D and do all to all alignments, and then run LAsort, 

all alignments against A will be first,

after that, all alignments of B against C and D will be next, but the alignments of B against A will not be at this location

after that all alignments of C against D will be next, but the alignments of C against B and the alignments of C against A will not be at this location.

Correct?

**Comment by pb-cdunn** [comment]
Two reads X and Y can have multiple alignments, in both forward and reverse-complement directions.  Personally, I prefer to call these "overlaps"; I call a calculated string of indels the *alignment*. But there are many overloaded terms in bioinformatics. Oh, well.

Every alignment has an *a* and a *b* read. That's just what they're called in that context.
