### ISSUE TITLE
sge killing off falcon jobs due to not enough memory

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#33]
Hi, Jason,

Assembling drosophila as a test.  I believe all jobs associated with directory 
0-rawreads
have completed and falcon is now working on directory
1-preads_ovl

A number of the jobs with names such as 1-preads_ovl/job_d9d5103/rj_d9d5103a.sh
did not complete, I believe due to sge killing them off due to high memory usage.

In the cfg file are sge parameters:

sge_option_da = -pe orte 1 -l mfree=30G
sge_option_la = -pe orte 2 -l mfree=6G
sge_option_pda = -pe orte 6 -l mfree=6G
sge_option_pla = -pe orte 2 -l mfree=6G
sge_option_fc = -pe orte 6 -l mfree=6G
sge_option_cns = -pe orte 6 -l mfree=6G

I'm not clear which sge option is used for this step.  
Could you please correct the table (below)?  That would answer this question 
and most every future question about which parameter to use when an sge parameter needs to be changed for a particular problem:

sge_option_da  used for making files in 0-rawreads
sge_option_la used for making files in 0-rawreads
sge_option_pda used for making files in 1-preads_ovl
sge_option_pla used for making files in 1-preads_ovl
sge_option_fc used for making files in 2-asm-falcon
sge_option_fc used for making files in 2-asm-falcon

(You *almost* say this in the documentation, but not quite, at least for me.)

Thank you!
David

**Comment by pb-jchin** [comment]
sge_option_pda = -pe orte 6 -l mfree=6G # for dalinger job on 1-preads_ovl stage
sge_option_pla = -pe orte 2 -l mfree=6G # for merging alignment file (*.las) for 1-pread_ovl

**Comment by dgordon562** [comment]
Thank you!

and I assume that:
sge_option_fc = -pe orte 6 -l mfree=6G
sge_option_cns = -pe orte 6 -l mfree=6G

are both for files in 2-asm-falcon?

**Comment by pb-jchin** [comment]
yes.  sge_option_fc need RAM when it reads all sequences into memory for constructing contig.  Namely, you will need some memory as big as the "titling path" (set of error corrected reads that covers the contigs and none of them is contained within each other) through the genome.  I don't have a good mathematical model for that yet, but I think it is typically 5 to 10x of the genome.

the error correction consensus (specified by sge_option_cns) typically does not use too much memory, 6G should be fine.  It is I/O intensive though since it randomly accesses the sequence data from the daligner database.  You should watch if I/O becomes your bottleneck.  If so, you will need different strategy moving data around.
