### ISSUE TITLE
faster restart suggestion

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#334]
When Falcon is in the midst of rp_ jobs and you restart it, you get 5000 of  (see below) before it decides to submit new jobs.  I'm assuming it is just checking on done flags for each job_ directory.  How about how a flag e.g., 0-rawreads/jobs_done that it checks.  If that flag is set, it doesn't need to check any of the thousands of job_*/*done flags.  That would cut restart time down from ~15 minutes (10 minutes so far and I don't have the patience to sit waiting to find the exact number) to a minute or so...
```
[INFO] Skipping already done task: task://localhost/d_0fb6_raw_reads
[INFO] Skipping already done task: task://localhost/d_0141_raw_reads
[INFO] Skipping already done task: task://localhost/d_0098_raw_reads
...
```

**Comment by pb-cdunn** [comment]
With fc_run1 (which uses pwatcher), the start-up time should be a few seconds, since all 'done' files are in the same directory. It's just one `listdir()`.

Yes, I'll use your suggestion when I get around to simplifying pypeflow, but not soon. I really want you to try `fc_run1`. Anyway, thanks for the timing number. That's always useful info.

**Comment by pb-cdunn** [comment]
This should be instantaneous now, via `fc_run1`, since it amounts to a single `os.listdir()`.

We *could* add something to suppress the INFO for done tasks, but 5k lines is really not that much for a single log-file. I think this is resolved.
