### ISSUE TITLE
using same dataset with different length_cutoff / length_cutoff_pr

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#342]
Hi, Chris,

Does it make sense to you that the same dataset will have the same number of daligner jobs *and* the same number of blocks, even though the length_cutoff and length_cutoff_pr are different?

If so, does this mean that I could run all the daligner jobs once, and then use the output (the job_ directories) for experimenting with various length_cutoff values without having to re-run the 0-rawreads daligner jobs?

Thanks!
David

**Comment by pb-cdunn** [comment]
> Does it make sense to you that the same dataset will have the same number of daligner jobs and the same number of blocks, even though the length_cutoff and length_cutoff_pr are different?

Yes. `length_cutoff` is only for seed-reads. The `DBsplit` options control the size of the DB, which (along with daligner memory settings) controls the number of jobs.

> If so, does this mean that I could run all the daligner jobs once, and then use the output (the job_ directories) for experimenting with various length_cutoff values without having to re-run the 0-rawreads daligner jobs?

Well, almost. You can definitely try *increasing* `length_cutoff`. However, it is the `-H` parameter to daligner. So *reducing* `length_cutoff` after daligner runs will not add extra seed-reads into `*.las` files. Also, **daligner** is sensitive to inputs; it ignores kmers with a hit-count above the dynamic threshold. So by increasing `length_cutoff` and re-running **daligner**, you might actually pick up more alignments.

Btw, you might prefer to set:
```
genome_size = 3000000000
seed_coverage = 50
length_cutoff = -1
```
so that `length_cutoff` can be auto-calculated.

If you think you are missing critical alignments, and if you know that you have extra memory available, you can try increasing `-M`. If you have only 1 job per machine, just use `-M0` to use (almost) all available memory. In either case, do *not* set `-t`.

The most leverage is in adjusting kmer sizes.

**Comment by dgordon562** [comment]
Thanks, Chris!
