### ISSUE TITLE
Falcon trying to redo earlier stages of assembly 

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#353]
Hi, Chris,

All of the daligner jobs were completed weeks ago.  The LAmerge were also completed.  Yet when I run Falcon, it first tried to start redoing the LAmerge jobs.  I killed it, fixed all the symlinks, and restarted.  Then it tried to redo the daligner jobs.  To add insult to injury, even though I specified 100 concurrent jobs, it was submitting jobs as fast as it could.  About 50 ^C's later, it had submitted over 1000 jobs with no signs of letting up.

Panic ensued.  Finally successfully killed the out-of-control fc_run.py

I write-protected all of the job_* and m_* directories so Falcon wouldn't damage the work it had done over the past few weeks.   I carefully checked and no damage had been done (except for just one sub.sh file).   I then tried a clean version of Falcon (without the changes I put in yesterday) with essentially the same crazy results.  (I did that just to be sure the problem wasn't my changes.)  The only difference was that it kept trying to create job_*/*.sub.sh files but was unable to overwrite those files since I had write-protected those directories.

I've had a similar experience in the past and here is what I think is happening:  I think that the date/time of the files are out of order due to my work fixing the symlinks.   So pypeflow thinks jobs need to be resubmitted.

What I need to know from you guys is which files pypeflow pays attention to for its dependency graph within the stages in 0-rawreads.   The done files?  The L1.las files?  The raw_read.*.las files?   Is there a way I can tell from looking at the source code which files are the "target" and "source" for a pypeflow task?   If I know that, then I can touch them in the correct order and thus Falcon should behave correctly.

Thanks!
David

**Comment by dgordon562** [comment]
Solved.  I needed to adjust the timestamp of rdb_build_done to be after the timestamp of raw_reads.db but before any of the daligner job timestamps.

I believe I had inadvertently touch'd rdb_build_done when fixing an earlier problem.

It still would be useful to have a list of the files that PypeFlow examines the timestamps of.

**Comment by pb-cdunn** [comment]
> It still would be useful to have a list of the files that PypeFlow examines the timestamps of.

We'll add more pypeflow debugging eventually. I'm glad you figured this out.

**Comment by dgordon562** [comment]
I'm seeing a similar problem now with the c_ tasks, but fortunately not as extreme.  For example, here is a c_ task that had completed, but fc_run.py is trying to re-run it.  I have not messed with the timestamps in any way of the files:

-rw-rw-r-- 1 dgordon eichler-vol26 72848682 May  3 15:21 out.00814.fasta
-rw-rw-r-- 1 dgordon eichler-vol26        0 May  3 15:21 c_00814_done
-rw-rw-r-- 1 dgordon eichler-vol26      305 May  5 09:15 c_00814.sub.sh
-rw-rw-r-- 1 dgordon eichler-vol26     2166 May  5 09:15 c_00814.sh

Why is fc_run.py trying to re-run this job?
What flags/timestamps does PypeFlow look at to decide whether to (re)run a c_ job?  
Under what conditions would PypeFlow want to rerun a c_ job when the done flag exists?

More generally, how can I determine the answers to these questions by looking at the source code?

**Comment by pb-cdunn** [comment]
I don't think we have a good way to write the pypeFLOW graph, but the source code is pretty simple. Look at `create_consensus_tasks()`:
* https://github.com/PacificBiosciences/FALCON/blob/master/falcon_kit/mains/run.py#L408

Its input (called "job_done" in its parameters) comes from `%s/m_%05d/m_%05d_done` in the corresponding merge task (in `create_merge_tasks()` immediately above it). If an earlier task is re-run (or any of its outputs touched), then all following tasks will be re-run too.

You might have better luck using `fc_run1` on the `master` branch. It uses `pwatcher`, which makes a distinction between the pypeflow task and the submitted job. Even if pypeflow says a task is out-of-date, the submitted job will not be re-run unless its sentinel file is missing. The "done" file is strictly for the pypeflow graph; the sentinel file is in a separate location, obvious if you run it. That gives you more control over which "jobs" to re-run. Since we never touch the task "done" file, this approach will do a bunch of file stat-ing on each call to `refreshTargets()`, but that's better than re-running the task.

**Comment by dgordon562** [comment]
Thanks!

That explains it:

-rw-rw-r-- 1 dgordon eichler-vol26 72848682 May  3 15:21 out.00814.fasta
-rw-rw-r-- 1 dgordon eichler-vol26        0 May  3 15:21 c_00814_done
-rw-rw-r-- 1 dgordon eichler-vol26      305 May  5 09:15 c_00814.sub.sh
-rw-rw-r-- 1 dgordon eichler-vol26     2166 May  5 09:15 c_00814.sh

But the following are more recent than the done and fasta above (probably due to fc_run.py going crazy yesterday):
-r--r--r-- 1 dgordon eichler-vol26 2972176404 May  3 21:06 ../m_00814/raw_reads.814.las
-r--r--r-- 1 dgordon eichler-vol26 0 May  3 21:06 m_00814_done
