### ISSUE TITLE
can falcon use local disk rather than nfs disk?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#36]
Hi, Jason,

Is there a method of having each of falcon's hundreds of jobs use /tmp or /var/tmp of the node it is running rather than the nfs-mounted disk?   The io to /tmp or /var/tmp (being local) is much faster and doesn't slow down nfs-mounted disk access for everyone else on the cluster.

If this requires source-code changes, how difficult would it be?  And how much improvement would it make (I assume each job would have to copy from nfs to local disk at the beginning of its run and then copy back to nfs after it has completed its run)?  Are these changes I could make myself?

just asking...

Thanks,
david

**Comment by pb-jchin** [comment]
The first stage of alignment data needs to be global accessible, since all the alignment data needed to merge sorted. If you want to keep it at local, it will needs many copy operations.  I do recommend to use a distributed file system for large genome.  The good part here is the overall I/O is more balanced between read and write.  If you can wait, you can just reduce the number of concurrent jobs so it can get by with slower NFS like systems. 

During the error correction stage, it needs a lot random access to the alignment data and sequence data, in my experience, this put a lot of stress even in a distributed file systems especially if the OS dose not cache the data. For example, even with a luster file system I have problem with regular `fopen("file","r")` calls as the OS dose not seem to cache the data.  However, I was able to get some reasonable performance by open a file with mmap (`fopen("file","rm")`) . This would be OS dependent though. It makes sense to make a local copy of the sequence data to reduce I/O through network. In this spot of the pipeline, it is easier to modify the source code to do local random access.

**Comment by dgordon562** [comment]
Is the error correction stage that titled "def run_consensus_task(self)" in the source which uses sge_option_cns?  This runs a script that runs LA4Falcon (see below) which appears to read a single *.las file and write a single *.fa file.  So are you suggesting moving the .las file to a local drive, running LA4Falcon on it writing the .fa to the local drive and then copying the .fa file  back to the network drive?  Are you also suggesting modifying LA4Falcon to use mmap calls?


source /net/gs/vol1/home/dgordon/falcon/FALCON-master/install/fc_env/bin/activate

cd ..
LA4Falcon -H12000 -o -f:raw_reads las_files/raw_reads.20.las |  fc_consensus.py --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 > /net/eichler/vol24/projects/whole_genome_assembly/nobackups/ecoli1/0-rawreads/preads/out.0020.fa

**Comment by pb-jchin** [comment]
@dgordon562 Exactly. Before I use mmap,  I have to copy the `raw_reads.db`, its associated files and  `raw_reads.*.las` to a local drive to improve the performance.  The `raw_reads.*.las` is job specific but the `raw_reads.db` can be shared by jobs. Namely, you only have to copy `raw_reads.db` once. What I did was manually copy that to local  /tmp/ (need to be big. SSD will be great), and modify the code to copy `raw_reads.*.las` on per job level. 

For copying `raw_reads.db`, the script will needs to know all computational node or detect the existence of file on fly. I have not have time to do that. Later, I found `fopen` with `mmap` solve my problem getting the data from Luster.

I have some patch modifying Gene's code to open file with `fopen/mmap', but I have not committed the code yet.
