### ISSUE TITLE
what causes preads shorter than the length_cutoff?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#360]
Hi, Chris and Jason,

For example, with a length_cutoff of 10kb, I'm seeing a pread of 500bp.  Isn't the length_cutoff the minimum length of a seed read?  And won't the pread derived from that seed read be at least as long as the seed read?   (Feel free to draw little picture...)

Thanks!
David

**Comment by pb-cdunn** [comment]
`length_cutoff` is used in `-H` arg to **daligner**, which means that only reads at least that long will be written as A-reads of A/B alignement pairs. If you see A-reads < 10k in the `*.las` files, then there is a bug. (You would have to cross-reference into the DB in order to know the read-lengths.)

The preads (in `0-rawreads/preads/out.*.fasta`) are "corrected", which in theory can include truncation, so they might be under the threshold. In fact, I have a fake example with exactly 2000b reads, all error-free by construction, and their preads are only about 1987 or so, which is actually an artefact of the consensus algorithm. With dirty reads, statistically there will be regions of low kmer-match coverage, so the results will be considerably shorter, as we do not keep portions of reads which lack sufficient coverage. We must hope that other reads of the discarded region of the genome have luckier coverage.

You can use `length_cutoff_pr` to discard the shorter corrected-reads. (I hate the word "preads". Too ambiguous.) However, I was discussing this with Mark Seetin today, who says that they typically use `length_cutoff_pr=0`.

Still, you have found a bug. The `-H` parameter of **LA4Falcon** is currently ignored. That's harmless, since we consider only the a-read as a seed, but we should stop using `-H` there.

**Comment by dgordon562** [comment]
Thanks, Chris.  Just to be sure I understand:

In the absence of bugs, there should be no read in 0-rawreads/preads of length that is significantly shorter than length_cutoff ?  (Because there are zillions of such...I'm generating right now a histogram to show you...)

**Comment by dgordon562** [comment]
Out of 8,944,785 preads generated with length_cutoff = 15000, there are 
13,113 preads of length 999 or less.  Might this not be a bug, but rather simply (as you explained above) that these reads were part of seed reads that were 15kb or longer, but that had reads matching to only 999bp or less of their length?

**Comment by pb-jchin** [comment]
the pread can be shorter the length cutoff. (trimming, chimers getting broken, etc.) see suppl. figure 1 from http://www.nature.com/nmeth/journal/v10/n6/extref/nmeth.2474-S1.pdf

**Comment by pb-jchin** [comment]
see suppl. fig. 15 too.

**Comment by pb-cdunn** [comment]
> In the absence of bugs

The bug is only that we pass `-H` which is ignored by **LA4Falcon**. It's not needed. Your output is fine. The shorter corrected reads are unfortunate, but `length_cutoff_pr` lets you control how many to keep.

**Comment by dgordon562** [comment]
thanks to you both!  Makes perfect sense!

**Comment by dgordon562** [comment]
Just to be sure I understand, here is a picture:
```
-------------------------------------------------------------------------------------------  (15kb seed read)
------ (read1, 600bp)
------ (read2, 600bp)
------ (read3, 600bp)
------ (read4, 600bp)
          ------------------------------------------------------------------------------------- (read5, 14kb)
          --------------------------------------------------------------------------------------(read6, 14kb)
          -------------------------------------------------------------------------------------- (read7, 14kb)
```
In such a case, LA4Falcon would create 2 preads (error-corrected reads):  one of length 600bp
and another of length 14kb, even though length_cutoff was 15kb.

Correct?

------

**Comment by pb-jchin** [comment]
yes. if there is no coverage or the coverage is smaller than the specified parameters, it will break into two.

**Comment by dgordon562** [comment]
Thanks, Jason!
