### ISSUE TITLE
FALCON parameters and their effect on assembly quality/run time?

### ISSUE THREAD

**Issue by StefanoLonardi** [PacificBiosciences/FALCON#381]
I want to assemble a 620Mb plant genome, 35% GC, with very low heterozygosity (essentially haploid).
We have 62x pacbio data, and I have been using the config file below. The parameters for `pa_HPCdaligner_option` and `ovlp_HPCdaligner_option` were suggested by Matthew Seetin (pacbio),
but I am using the other parameters from the ecoli config file, which might not be appropriate here.
```
input_fofn = input.fofn
job_type = torque
use_tmpdir = true
input_type = raw
length_cutoff = 12000
genome_size = 620000000
length_cutoff_pr = 12000
sge_option_da = -l nodes=1:ppn=16:nogpu,walltime=4:00:00,mem=30000mb -M stelo@cs.ucr.edu
sge_option_la = -l nodes=1:ppn=16:nogpu,walltime=4:00:00,mem=30000mb -M stelo@cs.ucr.edu
sge_option_pda = -l nodes=1:ppn=16:nogpu,walltime=4:00:00,mem=30000mb -M stelo@cs.ucr.edu
sge_option_pla = -l nodes=1:ppn=16:nogpu,walltime=4:00:00,mem=30000mb -M stelo@cs.ucr.edu
sge_option_fc = -l nodes=1:ppn=16:nogpu,walltime=4:00:00,mem=30000mb -M stelo@cs.ucr.edu
sge_option_cns = -l nodes=1:ppn=16:nogpu,walltime=4:00:00,mem=30000mb -M stelo@cs.ucr.edu
cns_concurrent_jobs = 64
pa_concurrent_jobs = 64
ovlp_concurrent_jobs = 64
pa_HPCdaligner_option =  -v -dal128 -M32 -e.70 -l4800 -s100 -k18 -h480 -w8
ovlp_HPCdaligner_option = -v -dal128 -M32 -h1024 -e.96 -l2400 -s100 -k24
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 8
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 16
```
I started running **FALCON** a few days ago, and to have an idea of the running time I checked `0-rawreads/run_jobs.sh` and I discovered that it contains 1,835,675 lines!! I searched for "#" in there, and there are 2,082 daligner jobs, 444,889 initial sort jobs, 17,342 level 1 jobs, and 667 level 2 jobs. Will **FALCON** run "forever"? Is there something wrong with the parameters?

**Comment by pb-cdunn** [comment]
pa_DBsplit_option = -x500 -s50

`-s50` means small blocks. GeneM estimates about 4GB of memory per block-comparison in this case, so your `-M32` is larger than you need. I'd use `-s200` (the default for **DBsplit**). Then you'll have 4x fewer blocks and 16x fewer block comparisons, so you'll have only `~100,000` lines in `run_jobs.sh`, and `~200` daligner jobs. (But then I'd use `-dal32` to ensure a good balance of blocks per job, which increase the number of jobs to `~800`-ish.)

But none of that affects total runtime much. Well, maybe a little, by using your resources more efficiently. Basically, you have a large genome, so it will take a lot of CPU hours. *daligner* is `O(n^2)`.

Possibly, your `length_cutoff` is too short. I like to use `length_cutoff=-1` so that I can control `seed_coverage`. But if your FALCON is up-to-date, then after the first level of daligner/merge/consensus jobs are done, you will have a `stats_preassembly.json` somewhere. (I don't remember the filename.) So you can at least check your numbers at that point.

**Comment by StefanoLonardi** [comment]
Thank you, this is really helpful.
Should `-s200` be changed in both `pa_DBsplit_option` and `ovlp_DBsplit_option`?
If i set `length_cutoff=-1` how would choose `seed_coverage` based on the `stats_preassembly.json`?

**Comment by pb-cdunn** [comment]
> Should -s200 be changed in both pa_DBsplit_option and ovlp_DBsplit_option?

The latter is much less important, since it will take much less time anyway. Feel free to experiment there. After stage-0 is done, you can always restart `fc_run`. (Just `rm -rf mypwatcher/` first.)

> If I set length_cutoff=-1 how would choose seed_coverage based on the stats_preassembly.json?

The stats file is just information after stage-0. It can help you diagnose problems.

You select `seed_coverage` based on other considerations. But `30` is usually fine. Be sure to see `genome_size` too. The calculated cutoff can be seen in `0-rawreads/length_cutoff` pretty quickly.

**Comment by StefanoLonardi** [comment]
Thank you!

**Comment by StefanoLonardi** [comment]
With this config
```
length_cutoff = -1
genome_size = 620000000
seed_coverage = 30
length_cutoff_pr = 12000
pa_HPCdaligner_option =  -v -dal128 -M32 -e.70 -l4800 -s400 -k18 -h480 -w8
ovlp_HPCdaligner_option = -v -dal128 -M32 -h1024 -e.96 -l2400 -s100 -k24
pa_DBsplit_option = -x500 -s200
ovlp_DBsplit_option = -x500 -s200
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 8
overlap_filtering_setting = --max_diff 120 --max_cov 180 --min_cov 10 --bestn 10 --n_core 16
```
I get "only" 206 daligner jobs, and 27889 sorting jobs (total of 112270 lines in `run_jobs.sh`). Much better.
