### ISSUE TITLE
fc_consensus 

### ISSUE THREAD

**Issue by lijingjing1** [PacificBiosciences/FALCON#406]
Hi ,i have a question about consensus,my consensus is very slowly,can you have any suggestion to make it faster ?ervery consensus running take ten hours but only generate 20 Mb corrected fasta,i do not finally it will cost how much times,so i kill the cp_*.sh jobs and running it with n_core(1/8) for test,and it give me the same result.

Backgroud：I have a genome about 3 Gb,total subreads 154 Gb,set length_cutoff = 5000(about 100 Gb data) to run falcon,and i have las_files/raw_reads.*.las average 60 Gb,i guess why it so big?

my sge node CPU is 24 memory is 64 Gb but Swap is 0,when i logging the node and top to see the jobs,below is the state cup use only 14.6% and 4.4% and the log do not refersh a long time.

```
PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                            
24955 nextomic  20   0 1008m 912m 1312 S 14.6  1.4   0:30.21 fc_consensus                                                                        
24952 nextomic  20   0  104g 2.8g 2.1g D  5.0  4.4   0:50.27 LA4Falcon
```

    LA4Falcon -H5000 -fo raw_reads las_files/raw_reads.88.las | fc_consensus --output_multi --min_idt 0.70 --min_cov 2 --local_match_count_threshold 2 --max_n_read 100 --n_core (1/8/24) --output_dformat

can you have any suggestion about my problem?

**Comment by pb-cdunn** [comment]
> memory is 64 Gb but Swap is 0

You mean you have no swap space on your node? Or you have no swap space *left*? Very important difference!

Anyway, your problem could be `104g` virtual memory use. Because of random access reads on the DB, we need to fit the entire DB into memory. Typically, the O/S can cache this, but your memory is only 64GB. Probably you are reading the DB directly from disk rather than via memory cache.

3GB is a large genome. A larger machine (with more memory) can help a lot. But you might have a shot if you re-run with less data. Use `-x1000` for **DBsplit** (so the DB is smaller), and these for automatic length_cutoff calculation:

    length_cutoff = -1
    seed_coverage = 30
    genome_size = 3000000000

That will give you a length_cutoff probably closer to 20k, which will reduce your overall runtime significantly.

You can also try `use_tmpdir=True`, which will let *LA4Falcon* stream onto a local disk and copy the entire fasta results back to the network drive. But I would deal with the low memory problem first, and then experiment with tmpdir.

**Comment by pb-jchin** [comment]
@lijingjing1 my first instinct is that your file system is not fast enough to handle the IO. As @pb-cdunn pointed out, depending on the local cache efficiency (very O/S and filesystem dependent), some job will stuck in I/O or worse swapping memory in-and-out between disk and memory.  Currently, due to the amount of data, one do need good amount memory and I/O bandwidth for efficiency computation for large genome assembly.

**Comment by lijingjing1** [comment]
Hi cdunn and jason ,i confirm the node have no swap space on.As you say if i set seed_coverage = 30,that means the length_cutoff is 10kb(about 89 Gb) and what's you mean 20k?,and if i just set seed_coverage = 30,beacuse it have 20-25% decrase and finally the corrected data just have about 24X.I just try length_cutoff = 10kb and set block size smaler to 200 Mb to avoid the align las file two big and make more jobs.

**Comment by pb-cdunn** [comment]
> and what's you mean 20k?

That was just a guess. In your case, the auto-calculated length_cutoff is about 10k? Note that you must also set `genome_size` in addition to `seed_coverage` in order to get auto-calculation. What is the *exact* length_cutoff auto-calculated for you? (`0-rawreads/length_cutoff`)

Also, if you have any further questions, it always helps to post your config when you submit questions, so we can see obvious errors.
