### ISSUE TITLE
Assembling relatevely short PCR amplicons

### ISSUE THREAD

**Issue by eugenegardner** [PacificBiosciences/FALCON#412]
We are attempting to use the FALCON assembler to assemble relatively short (between 6-9Kb) PCR-amplicon fragments. We have between 300x-2000x coverage for each of these amplicons, with the vast majority of reads covering the entire expected fragment (so reads in the 6-9kb range). For whatever reason, I can't seem to get FALCON to provide final assembly. I do get 10-500 preads (the preads4falcon.fasta found in the 1-preads_ovl folder) which, when aligned to my expected sequence, appear to be a fairly good consensus (albeit with a fair number of incorrect InDels). However, as stated earlier, I can't seem to get FALCON to perform final assembly to provide a finished contig in the 2-asm-falcon folder. I need these final files in order to hopefully perform diploid assembly using your new unzip algorithm.

Could you possibly provide a set of parameters that would be optimal for this kind of assembly (current parameters in my fc_run.cfg file below)?

Thanks!

```
[General]
#job_type = local

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = -1
genome_size = 8000

# The length cutoff used for seed reads used for pre-assembly
length_cutoff_pr = 3000


jobqueue = production
sge_option_da = -pe thread 8 -q threaded.q -l mem_free=4G
sge_option_la = -pe thread 2 -q threaded.q -l mem_free=4G
sge_option_pda = -pe thread 8 -q threaded.q -l mem_free=4G
sge_option_pla = -pe thread 2 -q threaded.q -l mem_free=4G
sge_option_fc = -pe thread 24 -q threaded.q -l mem_free=4G
sge_option_cns = -pe thread 8 -q threaded.q -l mem_free=4G

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 100 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
```

**Comment by pb-jchin** [comment]
Hi, by design, FALCON is for whole genome shot gun assembly rather for amplicon assembly. In the whole genome shotgun assembly we suppress repeats so we can get the non repetitive regions (relative to PacBio read length) assembled well first.  When you assemble PCR product of a short region in a genome, FALCON simple sees the whole thing like high copy repeats and filter them out.  

You could try to down sample your data and make the daligner block size even smaller ( reduce `-s50` in `pa_DBsplit_option` and `ovlp_concurrent_jobs` ) and increase the overlap filter thresholds (`--max_diff 100 --max_cov 100 ` in `overlap_filtering_setting`) to try to make it working. However, such amplicon assembly is really not inside the design scope of FALCON.
