### ISSUE TITLE
missing .las files for merge jobs

### ISSUE THREAD

**Issue by emmanuelconstantino19** [PacificBiosciences/FALCON#420]
Here's the error

LAmerge: Cannot open ./L1.1.23.las for 'r'
touch /scratch2/emmanuel.constantino/FALCON-integrate/FALCON-examples/run/rice/0-rawreads/m_00001/m_00001_done.exit
+ touch /scratch2/emmanuel.constantino/FALCON-integrate/FALCON-examples/run/rice/0-rawreads/m_00001/m_00001_done.exit
 returned: 256

I checked the directory and L1.1.23.las is missing.

What can be the solution to this problem?

**Comment by pb-jchin** [comment]
I do encounter such error from time to time in our file system.   what I usually find is that some previous related to block 1 or block 23 fails due to the file system issues. my typically work around is to pin down the exact corrupted file(s) due to the file system performance issue and re-run daligner for the specific comparison, and touch the the sentinel files, then re-start...

if you can't find the exact blocks but you can identify one particular job (for many block-block comparison), you can just re-run the jobs using the shell script in the job directory.

**Comment by emmanuelconstantino19** [comment]
grep "L1.1.23" job_*/rj_*.sub.sh

I did that to track if L1.1.23.las was ran on any job. I've seen that there were no .las files produced in that job. Am I on the right track on this one?

**Comment by emmanuelconstantino19** [comment]
I'm sorry that was supposed to be job_*/rj_*.sub.sh

**Comment by pb-jchin** [comment]
the `L1.1.13` is merged files, you need look for pattern like `raw_reads.*.raw_reads.*.[NC][1-4]`. You can see how those files are generated in the `rj_[0-9]+.sub.sh`. If they are not there, they got deleted after the merging. In such case, you need to run the job that generate `L1.1.13`

**Comment by emmanuelconstantino19** [comment]
Yeah i think I've seen that. I'm rerunning that job right now. Thank you!
