### ISSUE TITLE
quick question:  does raw_reads daligner compare *all* reads against *all* reads or

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#471]
does it just compare *all* reads against reads longer than length_cutoff?

thanks!

**Comment by pb-cdunn** [comment]
There is a different cutoff for the DB, typically about 50bp (e.g. `DBsplit -x50`). I am certain that nothing beneath that threshold is seen ever.

I am also certain that daligner will not report any overlaps where the a-read is shorter than `-H`, which is where we use the length-cutoff. It will not compare reads shorter than `-l` (typically 1000) because if a read is shorter, then its overlaps are definitely shorter. However, I am not sure whether job-partitioning excludes reads shorter than `-l`.

To answer your specific question, yes, daligner does compare reads longer than length_cutoff. The `-H` parameter is used only to filter the output, in `filter.c:report_thread()`.

**Comment by dgordon562** [comment]
Thanks, Chris.

Did you mistype (below)?

"To answer your specific question, yes, daligner does compare reads longer than length_cutoff."

To be more clear, if I set length_cutoff to be 15kb, will daligner compare two reads that are each 14kb?

**Comment by pb-cdunn** [comment]
Actually, no, I did not mis-type. It's hard to state all this clearly. I'm trying to help you with the settings which actually can reduce comparisons. But length-cutoff has no bearing on the number of comparisons.

And that's how we want it. Even though we would only use reads > 15kb as "seeds" for assembly, we will use shorter reads for overlap correction, to improve consensus.

**Comment by dgordon562** [comment]
Thanks, Chris.   So if I set length_cutoff to 15kb, daligner will still compare two reads that are each 14kb to each other.  Right?

**Comment by pb-cdunn** [comment]
Hi, David. Yes, that's correct. But it will not *report* overlaps of 14k v. 14k reads in the `.las` files. It *will* report 15k v. 14k overlaps, but not 14k v. 15k.

**Comment by pb-jchin** [comment]
to clarify, if the threshold is set to 15kb, here is the scenario 

(A) reads >= 15kb, (B) all reads : compared, this is equivalent to (A) all reads vs. (B) reads >= 15kb.

For error correction, reads < 15kb will not be used.

**Comment by pb-cdunn** [comment]
@pb-jchin, Yes, in the output you are correct. But the algorithm actually compares *all* reads in the DB that are at least as long as the shortest *overlap*, which is the `-l` parameter. The algorithm ignores the `-H` parameter (our length-cutoff), which is only for final dumping of `.las` files.

@dgordon562, I wasn't sure whether you are worried about total runtime/memory, or the final result. Sorry if I've caused confusion.

**Comment by dgordon562** [comment]
Thanks both Jason and Chris. 

 I was thinking that perhaps by increasing the length cutoff, I could make smaller las files (which both Jason and Chris infer is correct) and would also speed up daligner (which Chris indicates is not correct).  

Gene is usually very concerned with efficiency--it is strange that he would write a tool that would calculate the overlap between 2 reads (in this example, 2 14kb reads) knowing that he wasn't going to output anything about that overlap.   But I believe you...

**Comment by pb-cdunn** [comment]
> Gene is usually very concerned with efficiency

Well, Gene only added `-H` for HGAP. That's why it's called `-H`. It was very kind of him, actually.

... Hmm, that's not a bad idea, David. If we sorted the reads so that the long ones are restricted to a small subset of DB blocks, then we could exclude all block-pairs that do not involve that subset..... I guess that would be fewer jobs, but more memory per job. Maybe we're better off just filtering overlaps as they are produced. I'll look into that, maybe next week. Thanks!

**Comment by dgordon562** [comment]
Excellent idea (it is yours).  That would be even better than Gene reading all read pairs and just rejecting read pairs when both are less than the -M parameter.

Could you (when you are creating the blocks with DBsplit or whatever) make some blocks that have *no* reads that are shorter than length_cutoff?  In that case you don't even have to consider pairs of such blocks.

**Comment by pb-cdunn** [comment]
> Could you (when you are creating the blocks with DBsplit or whatever) make some blocks that have no reads that are shorter than length_cutoff? In that case you don't even have to consider pairs of such blocks.

Exactly! (But you mean *longer*, right?) Loading fewer reads could reduce I/O (well, "I"). However, this strategy would make the jobs highly unequal, which could utilize resources unevenly. And it could harm our ability to predict the amount of memory and time needed for each job. So I am leaning toward your first idea.

**Comment by dgordon562** [comment]
Yes, I mean a block of just short reads.  (sorry--making mistakes in email is worse for communication than making mistakes in talking)

You might want to first do a histogram to see what % of reads fall into that (short read) category.  If it is over 70.7%, then by ignoring pairs of such blocks, you will save 50% of the time.

**Comment by pb-cdunn** [comment]
Yes, 50% of the disk-read time, but 0% of the read-comparison time since Plan-B is to filter the comparisons. If we filter the reads on load, then we won't even compute kmers for the short reads, which could save some memory too.

But if we run a block with *only* long reads, then the kmer table (and whatever other datastructures daligner creates) would be 2x or more, which increases peak memory use. In order to balance the loads, we would need a fancier `DBsplit` to produce unequal-size blocks. The decision and implementation are non-trivial.

If the genome is so over-sampled that most of the coverage is in "short" reads (where "long" reads are those which give us 30x coverage), then the simplest solution is to increase `DBsplit -xNNN`. We could probably do that automatically, which is another good idea, far simpler than either one above.
