### ISSUE TITLE
enhancement:  changing # of sge jobs without killing running sge jobs

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#497]
This would *really* improve falcon.  You could write a little program that would interact with fc_run to change parameters:

pa_concurrent_jobs = 50
cns_concurrent_jobs = 50
ovlp_concurrent_jobs = 50

(and the new ones you are going to add as we discussed (grin))

Some daligner jobs might have been running for, say, 8 hours--it is such a shame to have to restart them just because you need to decrease or increase the total number of jobs.

You might need to decrease the # of jobs if another high priority project suddenly needs more resources.  You might want to increase the # of jobs if the load on the cluster has lessened.

(If you want some ideas of how to accomplish this, let me know--I have some.)

**Comment by pb-jchin** [comment]
@dgordon562  While it is possible, to chang some internal state of a running process needs careful design. If we keep add features, we will eventually have some bloating code that takes more and more of the responsibility of the job schedule (SEG/Slurm) in to FALCON itself. This may not be ideal.  To solve your problem, is it possible for the SGE administer to lower FALCON's job priority? Or temporary suspend jobs from the user until high priority job finished?

**Comment by pb-cdunn** [comment]
The whole point of the fs_based pwatcher was to allow you to restart and re-aquire already running jobs. However, internally we were forced to use blocking qsub calls, which *cannot* be re-acquired (obviously). So there is some complexity in supporting both blocking and non-blocking which has delayed any work on job re-acquisition.

For now, I recommend using a larger number of blocks, so the jobs can be smaller.

**Comment by dgordon562** [comment]
Great--thanks, Chris.

"For now, I recommend using a larger number of blocks, so the jobs can be smaller."  OK:

1)  to do this, decrease -s in pa_DBsplit_option.  correct?
2)  will this increase the # of job_ subdirectories?
3)  remind me (couldn't find this in the documentation):  what determines the number of m_ subdirectories?  not the block size?
4)  is the relationship between block size and daligner runtime roughly linear?
5)  why would you want to restart an already running job?
6)  i'm not familiar with the term "to acquire/reacquire a job" (not a lock).  what do you mean by this and why would you want to reacquire a job?
7)  after you've answered these questions, you might want to re-open this or put it in the documentation so others will benefit--it will be very useful information

Jason:  the problem with your idea is that suspending jobs does not release the resources.  If you have 1TB of memory and 100 cores (for example), and you suspend those jobs, no one else can use that memory or those cores.

**Comment by pb-cdunn** [comment]
>    to do this, decrease -s in pa_DBsplit_option. correct?

Yes. The number of blocks is inversely proportional to that. The number of block-by-block daligner comparisons is approx. `nblocks**2`

But the first thing is to check `HPC.daligner -Bn`. `4` is the default, which is fine, but if you had it higher, that's the first thing to reduce, since the runtime of a each Falcon job is almost proportional to `-B`. You could even reduce it to `-B2` if there is no other way to reduce the runtime of each job.

Specifically, with `-B4`, each job would run something like

    daligner raw_reads 4  4 5 6 7

That would perform 4v4, 4v5, 4v6, 4v7, 5v4, 6v4, and 7v4. With `-B2` you would have only 3 sub-jobs per job, instead of 7.

>    will this increase the # of job_ subdirectories?

Yes, and that's important. The goal is to spread the compuations over a larger number of jobs. If the high number of directories is a problem, let me know. We plan to move to a 2-level directory tree soon, and I could accelerate that.

>    remind me (couldn't find this in the documentation): what determines the number of m_ subdirectories? not the block size?

That should be the number of blocks. Or possibly half that? It's based on how HPC.daligner works.

>    is the relationship between block size and daligner runtime roughly linear?

Well, the number of comparisons is like the *square* of block-size, since we compare each read in block A to each read in block B. But I think the most expensive part is the overlap checking. Most possible overlaps are ignored, but if 2 blocks have high repetition I guess the runtime could be ... well .... different. But very roughly, if you reduce `DBsplit -s` by 2x, num block-comparisons should rise by 4x, and runtime for each block-by-block comparison, should drop by 4x.


>    why would you want to restart an already running job?

You wouldn't. For now, Falcon is meant to kill all running jobs if Falcon dies. If we supported job-reacquisition, we would leave running jobs running.

>    i'm not familiar with the term "to acquire/reacquire a job" (not a lock). what do you mean by this and why would you want to reacquire a job?

By "re-acquire", I mean an earlier Falcon might have run `qsub`, and after Ctrl-C (if we supported this mode), some jobs might still be in SGE. Upon restart, you would want Falcon to notice all existing job-output files, and also to *wait* on any still-running qsub jobs without resubmitting them. That's what I mean by "re-acquisition". Anyway, it's not supported right now.

>    after you've answered these questions, you might want to re-open this or put it in the documentation so others will benefit--it will be very useful information

Good idea. We are expanding docs for Sequel customers, actually. I'll pass this along.
