### ISSUE TITLE
simple question:  why delete mypwatcher when restarting Falcon?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#506]
First, rumor has it that prior to restarting falcon, you should:
rm -rf mypwatcher.dir

(or rename it) 

True?

If so, why?  What would happen if you didn't delete/rename it and then restarted Falcon?

Happy New Year!

**Comment by pb-cdunn** [comment]
Thank you! I hope your 2017 is a very good year, David.

The purpose of that directory was to facilitate re-acquiring an already running job in SGE. (That was a very interesting suggestion from a user, you!) It's not implemented though So for now, that directory just gets in the way. We might start deleting it always.

If you don't delete it, then any jobs which have already been run via SGE will remain in whatever state they were in. If they completed successfully, great! But if they failed, they will not be restarted, since they are mark as having been submitted already.

(I don't know what words to use for the different states.)

**Comment by dgordon562** [comment]
Thank you, Chris!
