### ISSUE TITLE
How to remove the intermediate file of m_* directories and jobs_* directories?

### ISSUE THREAD

**Issue by RyanBio** [PacificBiosciences/FALCON#517]
Hi, 
I need help about how to remove the intermediate file. My disk cann't store the huge amount of L1.*.las files in jobs_* directories and L2.*.las files in m_* directories any more! The total space i estimated can be reached 50T. 
When i finish a merge job such as m_00001, the directory has these las files:

```
L1.1.*.las -> ../job_*/L1.1.*.las
L2.1.*.las
raw_reads.1.las
m_00001_done
```

Before applying for more disk, i need to know which files can be removed after finishing a merge job.

Thanks.
Ryan

**Comment by RyanBio** [comment]
Keep the raw_reads.*.las only and it seems to be the essential file for next work.

**Comment by pb-cdunn** [comment]
That's correct.

We made a quick work-around recently to support a third level of las-file merging (for very large genomes), and we had to drop our deletion of las-files after merging. Sorry about that. To be specific, it's a tripling of disk-space (at most), since the `raw_reads.*.las` contain exactly the sum of all `L2`, which contain exactly the sum of all `L1`.

**Comment by pb-jchin** [comment]
@RyanBio Unix's `find`, `xargs` and `rm` commands are your friend. For example, 
```
find 0-rawreads -wholename "*job*/*L1*las" | xargs rm
```
will delete all `L1.*.*.las` files.    Use it with caution and do `man find`, `man xargs` to learn more if you wish.
