### ISSUE TITLE
if change config file and restart falcon, old config parameters continue to be used.  why?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#546]
Hi, Chris,

All of my jobs are in qw state waiting on a resource.  So I removed that resource requirement from my cfg file and restarted falcon.  But all jobs go into qw state waiting again on that resource.  I notice that the  file:

0-rawreads/preads/cns_00158/task.json

contains the information from the old cfg file from an earlier run.  I've been through this several times.  Please re-write task.json files after restarting falcon.

Thanks!
David

**Comment by dgordon562** [comment]
Or perhaps falcon is reading from
0-rawreads/task.json
and thereafter ignoring the cfg file?

**Comment by dgordon562** [comment]
No, that didn't work, either.   suggestions, please?

**Comment by pb-cdunn** [comment]
I had to make some changes so that our **pypeflow** version (for development and github users) and our **pbsmrtpipe** version (for customers) have 1:1 tasks. That meant I needed "scatter" tasks to define the parallel tasks, and "gather" tasks to gather parallel results. The scatter task dumps one big JSON file which has a JSON-list of JSON for each parallel task. If you change cfg, you need to remove files from the scatter-task directory before re-running. See `0-rawreads/daligner-scatter/scattered.json`

**Comment by pb-cdunn** [comment]
(And you're right: We should force scatter-tasks to be re-run for any change to cfg. They are quick anyway.)

**Comment by dgordon562** [comment]
I tried hiding 0-rawreads/daligner-scatter/scattered.json but rather than recreating it, falcon just crashes.  So instead I will unhide it and edit it.  Does this mean that any change in parameters must be changed in both the cfg file *and* in 0-rawreads/daligner-scatter/scattered.json   ?  Or is cfg ignored and I need to change just in 0-rawreads/daligner-scatter/scattered.json ?  Or does it depend on which stage it is in?

**Comment by pb-cdunn** [comment]
Delete the `daligner-scatter` directory if you alter cfg. That might be enough.

* If the number of daligner jobs does not change, then the passed jobs will be skipped. (Pypeflow does not care about time-stamps.)
* If the number of daligner jobs *does* change, then you would need to restart everything. Sorry.

**Comment by dgordon562** [comment]
Thanks, Chris!

**Comment by dgordon562** [comment]
Well, that didn't work.  jobs are still being submitted with the old resource values.  is it possible that I need to delete/edit the daligner-scatter directory *and* all of the 0-rawreads/preads/cns_*/task.json files as well?

**Comment by pb-cdunn** [comment]
> Do I have to redo 2 weeks of daligner jobs just to change something in the cfg file?

No, I don't think so. But I think I've missed the obvious one: You need to delete the 'build_rdb' task directory, because that is where we ran `HPC.daligner`, which is want propagates your settings.

**Comment by dgordon562** [comment]
build_rdb is not in my 0-rawreads nor is it at the same level as 0-rawreads.  Where is it?

(My Falcon is from late November.  Perhaps build_rdb was introduced more recently?)

**Comment by dgordon562** [comment]
I did, however, find this:

0-rawreads/merge-scatter/task.json

Could it be the source of the settings?

**Comment by dgordon562** [comment]
After deleting merge-scatter/task.json and merge-gather/task.json and the entire daligner-scatter directory (as you instructed above), falcon crashes:

[INFO]Num still unsatisfied: 0
Traceback (most recent call last):
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 484, in main
    main1(argv[0], args.config, args.logger)
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 145, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 230, in run
    daligner_tasks, daligner_out = create_daligner_tasks(rawread_dir, scattered_plf)
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 25, in create_daligner_tasks
    content = json.loads(open(scatter_fn).read()) # array of descriptions
IOError: [Errno 2] No such file or directory: '/net/eichler/vol26/7200/dgordon/clint6/0-rawreads/daligner-scatter/scattered.json'

**Comment by dgordon562** [comment]
I should mention that it is desirable to be able to change sge parameters now and then during a falcon assembly.  In the past I've used this functionality when, for example, I find some types of jobs require more (or less) memory than I originally thought.   Or, for example, after Falcon has run for many days and starts a new stage, I find I've set the sge parameters for the new stage incorrectly.  It used to be very easy to change sge parameters and restart falcon.

**Comment by coreywischmeyer** [comment]
Falcon-integrate commit 2b5cb6375249e60b34c8183fc5a4fe76501e611c

I'm having a similar issue, I've tried deleting the `task.json` files in `preads/cns_*` then restarting but the settings still stick around. 

Did anyone come  up with a list of config/json files to delete in order to have the settings update? Is there a file I can edit (perhaps one of the scatter json files) until this issue is fixed?

**Comment by dgordon562** [comment]
Is this something that could be fixed?

**Comment by pb-cdunn** [comment]
If I could work on just pypeflow, I would fix this right away. But the likelihood is that we will move to a different workflow engine, and in that case the whole issue could change.

If I get a bit of time over the weekend, I'll try to find a quick fix.

**Comment by AdamStuckert** [comment]
I am re-upping this issue to see if anyone has an easy fix. I had to change my memory requirements because my assembly ran out of memory. However, falcon is not recognizing the new memory parameters and it submits with the old memory parameters. I end up getting compute nodes that have too little memory so my assembly just fails again.

**Comment by pb-cdunn** [comment]
You can delete the "split" and "chunks" directories for the given distributed tasks and re-run. The splitter sets up an array of work to be accomplished, so you have to delete it in order to regenerate the scripts.

If you have too much trouble with **pypeflow**, you can try our new experimental **snakemake** workflow. Feel free to post comments here, as we are actively developing this (on the `snake` branch of **pb-assembly** repo):

* https://github.com/PacificBiosciences/pb-assembly/blob/snake/snake/clr/falcon/falcon.snakemake
