### ISSUE TITLE
easy question about .raw_reads.bps

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#56]
I see daligner processes running:

daligner -v -t16 -H12000 -e0.7 -s1000 raw_reads.3 raw_reads.1 raw_reads.2 raw_reads.3

Where are these "files" raw_reads.3 raw_reads.1 raw_reads.2 ?

I'll bet daligner pulls them out of .raw_reads.bps

Correct?

**Comment by pb-jchin** [comment]
Those are some "logical partition" of the read db. please check https://dazzlerblog.wordpress.com. specially https://dazzlerblog.wordpress.com/2014/06/01/the-dazzler-db/ 

Here is the relevant paragraph:

Divide the database <path>.db or <path>.dam conceptually into a series of blocks referable to on the command line as <path>.1, <path>.2, … If the -x option is set then all reads less than the given length are ignored, and if the -a option is not set then secondary reads from a given well are also ignored. The remaining reads, constituting what we call the trimmed DB, are split amongst the blocks so that each block is of size -s * 1Mbp except for the last which necessarily contains a smaller residual.

**Comment by dgordon562** [comment]
Thanks for the reference!

And this paragraph is also relevant:


(c) .FOO.bps
a binary compressed “store” of all the DNA sequences. It is M/4 bytes in size where M is the total number of base pairs in the database.

**Comment by pb-jchin** [comment]
Yes. Gene's blog is very informative.  And it is important to know some key details for optimizing the parameters used for assembly.
