### ISSUE TITLE
Loss of subreads

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/FALCON#570]
After we run fasta2DB and DBsplit, we'll get a database which stores all reads.

![1](https://user-images.githubusercontent.com/4936625/29309835-f53338c4-81dd-11e7-85c7-6a38d64e4f36.png)

But I notice that only one subread of several subreads from the same one polymerase read will reserve. It will cause loss of data. So I want to know:
Should I rename headers of each read so these reads will not be regarded as subreads from the same one polymerase read?

**Comment by lijingjing1** [comment]
you can set pa_DBsplit_option = -x1000 -s200 -a    -a mean all .

**Comment by nottwy** [comment]
谢谢你哦。

**Comment by gconcepcion** [comment]
We only use -a in coverage limited situations. By including -a, you are saying that you want to use all subreads from all ZMWs. By omitting -a, you are saying you only want to include the BEST subread from each ZMW. If you are not in a coverage limited situation, then this will only improve the quality of your assembly. If you *are* coverage limited, you might want to include -a to leverage all of the data, but with the tradeoff that assembly artefacts will be introduced due to some poor quality subreads being included.
