### ISSUE TITLE
some daligner jobs cause error

### ISSUE THREAD

**Issue by IEkAdN** [PacificBiosciences/FALCON#577]
[stderr.txt](https://github.com/PacificBiosciences/FALCON/files/1290865/stderr.txt)
I tried to assemble a human genome, but some of daligner jobs failed with the error massage as attached. Could you please tell me what the message means and how to restart the assembly?

**Comment by nottwy** [comment]
Please attach the stderr file of the task job_41ae.

**Comment by IEkAdN** [comment]
Thank you for your reply.
I thought the attached file was the stderr file of the task job_41ae, but is that wrong?
The path of the attached file is `0-rawreads/job_41ae/pwatcher.dir/stderr`.

**Comment by nottwy** [comment]
Yes. The reason why I don't think it's the flle under pwatcher.dir is there isn't explicit error reason in the file. In general, the reason of error is clear. I read your file again and find that it may be caused by timeout. So maybe it's caused by your computation cluster. How about just trying submitting this task again?

**Comment by IEkAdN** [comment]
I am sorry for my late reply. My problem seemed to be related to [https://github.com/thegenemyers/DALIGNER/issues/43]
, and now I could restart the assembly successfully.
Thank you for your advice.
