### ISSUE TITLE
Need ability to insert a module command into run script

### ISSUE THREAD

**Issue by stetner** [PacificBiosciences/FALCON#580]
Trying to insert a module load command into the run scripts as I need to override the default python to run falcon.  Would the only way be to alter the code?

/opt/Modules/falcon/20170823/fc_env/lib/python2.7/site-packages/falcon_kit/bash.py

Doug

**Comment by stetner** [comment]
Also changed:
/opt/Modules/falcon/20170823/fc_env/lib/python2.7/site-packages/pwatcher/fs_based.py

**Comment by pb-cdunn** [comment]
Just noticed this old question. Interesting.

In other words, you have a different environment on the server than on the remote node?

The problem is that we have to wait for files to be available on the remote node. We have all sorts of filesystem latency for various users. But we do assume that `task.sh` is available after `run-JOBID-bash.sh` is found. So your idea might work.

But the easiest short-term change would be to fork pypeFLOW and hack `pypeFLOW/pwatcher/mains/job_start.sh`
