### ISSUE TITLE
Is FALCON actually generating a phased assembly ?

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/FALCON#582]
Dear developpers,

I performed the assembly of my genome with FALCON and I corrected the indels with Illumina reads. So, here, I have a great assembly but I know I have some haplotigs in my primary contigs, because the primary contigs and its haplotigs are too differents. To correct that, I have launched Haplomerger2 on my FALCON assembly, which generated a higher quality assembly, with less contigs and more genes found (with BUSCO). But, at this step, I was thinking that I would loose the phase with Haplomerger2, because some contigs/haplotigs are merged by HM2. In order to know if I have to keep this Haplomerger2 step, I looked at whether the Falcon assembly was better phased than the one after haplomerger2. For that, I used Whatshap, a tool generating phased VCF from my assembly, by these steps : 

- I aligned my Illumina reads on the assembly and performed a variant calling with Freebayes
- I generated a phased VCF with Illumina reads and corrected Pacbio reads thanks to Whatshap
- For each position in my VCF, I look at my FALCON (or HM2) assembly to see if the variant is from haplotype1 or 2

And, if FALCON assembly have a majority of variants from haplotype1 (or 2) and HM2 not, I can consider that FALCON assembly is better phased. 

But here, I see that both FALCON assembly and HM2 assembly are not well phased. So, in my opinion, I have to perform the HM2 step and then I have to phase my assembly with Whatshap. What do you think about that ? Is it normal that my assembly is not phased after FALCON?

Thank you very much,
Amandine

**Comment by gconcepcion** [comment]
Hi Amandine,

After performing a FALCON assembly, your genome will NOT be phased. If you want to phase your genome, you need to run the FALCON_unzip pipeline found here:
https://github.com/PacificBiosciences/FALCON_unzip

Also, polishing with Illumina is generally unecessary. If you have enough data to assemble, then you have enough to also polish. Sometimes performing 2 rounds of polishing with the raw pacbio data can reduce your error rate significantly and obfuscate the need to short reads.

**Comment by a-velt** [comment]
I have perform a complete FALCON run, with the FALCON unzip step. However I see that my genome is badly phased when I compare to results after Whatshap. That's why I wanted to know if it was normal for the phase to be bad after Falcon-unzip, knowing that I used pacbio reads with a coverage of 120X?

**Comment by gconcepcion** [comment]
Hi Amandine,

This question is more appropriate for the FALCON_unzip issues page, which is why I closed it here.
 
FALCON_unzip is a highly experimental pipeline that was designed specifically to phase the plant & fungal genomes described in the 2016 Nature methods paper, however many people have used it successfully to aid their phasing efforts in a wide variety of species.

I can't comment on whatshap or haplomerger2 as I have never used them before and i'm afraid there are probably alot of assumptions being made that don't match with what the nature of FALCON_unzip output really is. 

Consider this section of the FALCON docs before deciding what next to do with your FALCON_unzip output:
[http://pb-falcon.readthedocs.io/en/latest/faq.html#why-don-t-i-have-two-perfectly-phased-genomes-after-falcon-unzip](url)
