### ISSUE TITLE
Deprecated setting in config

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON#599]
Hi,
Could you please update the `cfg` files inside `example` folder with the latest setting names?

```
/home/mictadlo/projects/FALCON/falcon_kit/run_support.py:194: UserWarning: Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately
  "Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately")
/home/mictadlo/projects/FALCON/falcon_kit/run_support.py:199: UserWarning: Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately
  "Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately")
[INFO] No target specified, assuming "assembly" as target 
/home/mictadlo/projects/FALCON/falcon_kit/run_support.py:456: UserWarning: Unexpected keys in input config: set(['pa_concurrent_jobs', 'ovlp_concurrent_jobs', 'jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" % repr(unused))
```
Thank you in advance.

Michal

**Comment by skingan** [comment]
Thank you, Michal. We will update this.
Sarah

**Comment by olechnwin** [comment]
Hi,
I'm confused about this setting. Isn't the message "Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately" suggest there should be da_concurrent_jobs and la_concurrent_jobs separately for daligner and las-merge step?
However, the updated cfg file inside example only has da_concurrent_jobs.

Also, the reason I'm asking is because I changed my cfg file to la_concurrent_jobs and da_concurrent_jobs but the daligner was run with la_concurrent_jobs. I don't understand why.

**Comment by pb-cdunn** [comment]
@olechnwin, `pa_concurrent_jobs` was deprecated long ago. More recently, we've switched to using `njobs` in the respective sections, e.g. `[job.step.da]`.

* https://github.com/PacificBiosciences/FALCON/wiki/Configuration

**Comment by olechnwin** [comment]
There are so many different version of documentations, it's hard to know which one is current. Does that mean http://pb-falcon.readthedocs.io is old and no longer applicable?
Is there a tutorial for the new version?

**Comment by pb-cdunn** [comment]
Unfortunately, yes, readthedocs is maintained separately and thus out-of-date.
