### ISSUE TITLE
relationship between genome size and min_cov

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/FALCON#601]
Dear developers,
Because of a change of parameter --min_cov (in falcon_sense_option) from 3 to 1, the size of my genome increase a lot.

Could you tell me the mostly possible reason: 
why the change of the min_cov from 3 to 1 makes the size of my assembled genome becomes large?

falcon_sense_option =       --output_multi --min_idt 0.70 --min_cov 1 --max_n_read 350 --n_core 16

**Comment by skingan** [comment]
Dear nottwy,
The "min_cov" parameter of falcon_sense determines the minimum coverage required to calculate a consensus sequence during pread generation. By reducing this parameter, I expect that you have generated more preassembled reads, many of which will be low quality because they lack raw read support. This could explain why you have a longer assembly.
Sarah
