### ISSUE TITLE
How to skip LAcheck

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/FALCON#604]
dear developer,

I have set the flag skip_checks=true, but it still generates LAcheck commands.
It wastes me lots of time.
Could you help me?
thanks.

**Comment by pb-cdunn** [comment]
That might have gotten lost. We can try to re-enable that flag in an upcoming release.

However, we only added it because it was sometimes crashing, when we could avoid the bad .las files in various ways. It doesn't seem to be crashing anymore.

If it's working, I'm very surprised if LAcheck takes significantly more time than LAmerge. Are you sure about that? It's possible that *both* are slow, if your filesystem is slow for streaming large files. You can try `use_tmpdir = true`.
