### ISSUE TITLE
Difference between /2-asm-falcon/p_ctg.fa and /2-asm-falcon/proper/p_ctg.fa

### ISSUE THREAD

**Issue by uceleste** [PacificBiosciences/FALCON#623]
Hi All,

At the end of the Falcon assembly process I obtained two different p_ctg.fa output.

One is in the folder /2-asm-falcon/p_ctg.fa
One is in the folder /2-asm-falcon/proper/p_ctg.fa

The one in the /2-asm-falcon/proper/ folder is a little bigger than the other one.

What are the differences between the two assemblies?
Which of the two should I consider as the final assembly?

Thanks

**Comment by pb-cdunn** [comment]
I think you're using old code.

Originally, Falcon neglected the first read (except its overlap with the second read) on each contig. That made graph traversal a little easier, and the omission was irrelevant in a large genome.

A few months ago, we added those to the contigs. That was more "proper", but it broke Unzip. So we did both ways for awhile. (I used the word "proper" as this is similar to "proper overlaps", but maybe it's not quite the right word.)

Since then, we have improved how Unzip deals with the starts of reads, so the "proper" contigs are now used always. We don't generate the "improper" contigs at all anymore.

The "proper" assembly is a little better. But you're better off upgrading your code.
