### ISSUE TITLE
Add support for slurm-based clusters

### ISSUE THREAD

**Issue by lexnederbragt** [PacificBiosciences/FALCON#71]
Allow SLURM based clusters, not just SGE. I have started working on this and am preparing a pull request.

**Comment by conte1** [comment]
Hi Lex,

I was also interested in being able to run FALCON with a SLURM cluster. Before I dive into this, I was curious how far you have gotten on this.

Thanks,
Matt

**Comment by lexnederbragt** [comment]
Check out my fork at https://github.com/lexnederbragt/FALCON. I have it working on our cluster. But there is a lot of code (semi)duplication so I was thinking of refactoring a few things.

   Lex

**Comment by pb-cdunn** [comment]
We are thinking of using this for slurm support:
* https://github.com/pb-cdunn/saga-python/tree/master/src/saga/adaptors/slurm

Would that work for everyone here?

@lexnederbragt, if you want to contribute to FALCON, base off the diconsensus branch. Otherwise, it would be hard to merge later.  In fact, look at the diconsensus branch of [FALCON-modules](https://github.com/pb-cdunn/FALCON-modules), as we have moved the submodules into a separate repo.

**Comment by lexnederbragt** [comment]
@pb-cdunn Can't tell whether the code you refer to would work as it is a bit over my head. I am not sure when I will have time again to work on this, but if I do I'll base it on the branch you mention.

**Comment by conte1** [comment]
Thanks for sharing, Lex. I'll give it a shot.

**Comment by pb-jchin** [comment]
@lexnederbragt thanks for sharing.

**Comment by pb-cdunn** [comment]
We might switch to SAGA someday, but for now see #107.
