### ISSUE TITLE
Available input for Falcon-Unzip

### ISSUE THREAD

**Issue by mentorlg** [PacificBiosciences/FALCON#715]
Hi, I have questions about Falcon-Unzip assembler.

1. Is this possible to assemble reads using only Falcon-Unzip?
    In the tutorial, Falcon-Unzip uses Falcon results as input.
    Do I have to contig assembly prior to assemble with Falcon-Unzip..?
    Is this impossible using just reads data as input of Falcon-Unzip?

2. Can I use 'assembled contigs from other assemblers' as input for Falcon-Unzip?
    I'm not sure that Falcon-Unzip is compatible with other assemblers like Canu, SOAPdenovo2, Platanus...and so on.

I look forward to hearing from you soon.

Sincerely,
Amelia

**Comment by gconcepcion** [comment]
Hello,

Falcon-Unzip is not an assembler. Based on overlap data that was generated during the FALCON assembly process, Falcon_Unzip attempts to extract alternate allele information in order to output alternate contigs a process referred to as "Unzipping".  It is dependent on files and overlaps that were generated during the FALCON assembly process and thus you cannot run Falcon-Unzip with output from another assembler.
