### ISSUE TITLE
your CHM1 assembly vs mine

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#75]
Hi, Jason,

Your CHM1 assembly has a higher N50 and better contiguity overall than mine does, even though we are using the same reads.

Is this due to different length cutoffs?  Which did you use? (could you just supply me your entire cfg file, please?)

Anything else that might explain the difference?

Thanks,
david

**Comment by pb-jchin** [comment]
Here is the relevant part of the parameters I used. Note that my length cutoff for preads (length_cutoff_pr = 6000) is smaller than `length_cutoff = 10000`. It means that I tried to boost the coverage of the preads by recruiting some more p-reads between 6000 to 10000. 

```
# The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000

# The length cutoff used for seed reads used for pre-assembly
length_cutoff_pr = 6000
pa_HPCdaligner_option =  -v -dal128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 10
falcon_sense_skip_contained = True

overlap_filtering_setting = --max_diff 40 --max_cov 25 --min_cov 2 --n_core 24
```


My stats from this assembly is  (with an experimental option `--lfc` for `fc_ovlp_to_graph.py`, my command is  `fc_ovlp_to_graph.py preads.ovl --min_len 6000 --lfc > fc.log`)

```
Contig Stats
#Seqs   3145
Max     31418753
Total   2781558109
n50     5860842
n90     1015758
n95     517058
```

**Comment by dgordon562** [comment]
Thanks, Jason!

I would like to replicate your results.  The ones that I used that were different were:
length_cutoff = 9000
length_cutoff_pr = 9000
so I'll obvious change those to yours.  

Others that differed were:
falcon_sense_option had one additional parameter:
 --local_match_count_threshold 2
(hell if I know what that is--shall I delete it?)

and my overlap_filtering_setting had the different values of  --max_diff 60 and  --max_cov 60
Shall I change those to yours?

Shall I run fc_ovlp_to_graph.py with your --lfc?

What version Falcon did you use?
How can I tell which version I am using?

**Comment by pb-jchin** [comment]
@dgordon562 apologize, I realized the parameters I sent is for an updated consensus code, however, I think it should not matter much. The option `--local_match_count_threshold` is no longer used in the new code.  The "--lfc" is an option I add, what it does is to use some "local flow constrain rules" to resolve repeat instead of "best overlap rules". In my experience, there is no definite better or worse in different senario between those two.  What I did is some quick experiments. You can re-do the last part of the assembly quickly to test out a couple of different parameters by re-run the `run_falcon_asm.py` script. (You can comment out the lines before "find..." as those are not algorithm parameter I/O intensive part.) 

For the `overlap_filerting_setting`, please refer to the doc here https://github.com/PacificBiosciences/FALCON/blob/master/doc/falcon_manual.md#overlap-filtering to see what it means.  Ideally, you want to include all reads with unique 5'- and 3'- ends, but removing all reads ends in repeats as they create forks which may not be resolved anyway. Measure the overlapping is one way to infer that. However, it is not perfect and it depends how much coverage you have to set the parameter.  After I get the diploid resolution in certain shape, I can start to think some better way to auto estimate those parameters. You will have to do some ball park estimate with your intuition for now.

**Comment by dgordon562** [comment]
Thanks.  

So will I be able to reproduce your results using the cfg you posted above?

**Comment by pb-jchin** [comment]
If you use the same length cutoff, I will expect you get similar results.

**Comment by dgordon562** [comment]
Thanks!

What version Falcon did you use?
How can I tell which version I am using?

**Comment by pb-jchin** [comment]
`git status` will give some hint about the git revision of your local repository. I recommend using git's revision number to track.  If you do some modification, the better thing to do is to fork the code base and keep your changes version controlled.  I am constantly testing new ideas for various algorithm improvement.  I am using `diconsensus` branch tagged with `CHM1_P6_2` assembling the latest P6 CHM1 data now.   It is unlikely I will do much work along the older P5 dataset.
